### ISSUE TITLE
Documentation update:  Include scope

### ISSUE THREAD

**Issue by benbeyerlein** [google/googleapps-message-recall#4]
I was getting an 'access_denied' error until I added this scope (in addition to the Gmail scope).
https://www.googleapis.com/auth/admin.directory.user.readonly

Separately, the instructions to create a service account with client ID are slightly different with the recent updates to the Google Developer Console.

**Comment by mirons-google** [comment]
Thanks. When you say 'in addition to the Gmail scope' which scope are you referring to?

**Comment by benbeyerlein** [comment]
The scope in my first post (https://www.googleapis.com/auth/admin.directory.user.readonly).

**Comment by miketruty** [comment]
This is correct.  I used to have this in my docs but I removed it as it seemed to admin was auto-added.  But it's not now and it is required so I've added it back to the docs.  I've also updated the docs to reflect a number of other updated flows in the Cloud Platform pages.  Thank you!
